#example:

#myapp:
#  service: project1
#  test1: script1
#  test2: script2
#  array:
#    -
#      key1: value1
#      key1detail: neco
#    -
#      key2: value2
#    -
#      key3: value3
#  MultiLineString: |
#    1st line
#    2nd line
#    3rd line

name: GitHub Action test
on: [push] #push - kdykoliv přijde commit, spusť tuto akci
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello world!" #za pomlčkou mezera
      - run: tree 