#example:

#myapp:
#  service: project1
#  test1: script1
#  test2: script2
#  array:
#    -
#      key1: value1
#      key1detail: neco
#    -
#      key2: value2
#    -
#      key3: value3
#  MultiLineString: |
#    1st line
#    2nd line
#    3rd line

name: GitHub Action test
on: [push] #push - kdykoliv přijde commit, spusť tuto akci
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #action that checked out your repository to the computer that runs the action
      - uses: actions/setup-node@v2 #Optionally downloading and caching distribution of the requested Node.js version, and adding it to the PATH
        with:
          node-version: '14.17.0'
      #- run: node -v
      #- run: echo "hello world!" #za pomlčkou mezera
      #- run: tree  #zobrazení stromové struktury
      - name: instal node modules
        run: yarn
      - name: build the project
        run: yarn build
      - name: setup finish
        run: echo "hotovo!"